### ISSUE TITLE
Update clj-yaml to the latest version

### ISSUE THREAD

**Issue by luissantos** [babashka/babashka#1532]
**Is your feature request related to a problem? Please describe.**
The clj-yaml version bundled with babashka doesn't support multiple documents per file. 

**Describe the solution you'd like**
Upgrade to v1.0.26 or above.

**Describe alternatives you've considered**
Splitting the yaml document and parsing each document individually.  

**Additional context**
Error while parsing the file
```
----- Error --------------------------------------------------------------------
Type:     org.yaml.snakeyaml.composer.ComposerException
Message:  expected a single document in the stream
 in 'reader', line 1, column 1:
    apiVersion: backstage.io/v1alpha1

```

**Comment by borkdude** [comment]
We need to get a new clj-yaml release since I purposely went back to the previous version of clj-yaml since it caused an issue with native image. This has been fixed on master: https://github.com/clj-commons/clj-yaml/commits/master
But we need a new release to bump it in babashka. cc @lread

**Comment by lread** [comment]
Happy to cut a new clj-yaml release, but the current release of clj-yaml is `1.0.26` which uses `org.flatland/ordered` 1.5.9. Was this version of `ordered` problematic?

```
❯ clojure -Stree -Sdeps '{:deps {clj-commons/clj-yaml {:mvn/version "1.0.26"}}}' 
org.clojure/clojure 1.11.1
  . org.clojure/spec.alpha 0.3.218
  . org.clojure/core.specs.alpha 0.2.62
clj-commons/clj-yaml 1.0.26
  . org.yaml/snakeyaml 1.33
  . org.flatland/ordered 1.5.9
```

We have since since bumped `org.flatland/ordered` to `1.15.11`.

**Comment by borkdude** [comment]
@lread You're right, 1.0.26 should not be problematic. I'll bump now!

**Comment by borkdude** [comment]
Bumped on master.

@luissantos You can use:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

to download/install the dev build (once the master build finishes) until the next release.

**Comment by luissantos** [comment]
@borkdude Sorry to disturb but I'm still getting the same error.

```

----- Context ------------------------------------------------------------------
 2:
 3:
 4: (defn parse-yaml []
 5:   (->>  #_(clojure.string/split (slurp "squads.yaml") #"---")
 6:         (yaml/parse-string (slurp "squads.yaml"))
            ^--- expected a single document in the stream
 in 'reader', line 1, column 1:
    apiVersion: backstage.io/v1alpha1

```

**Comment by luissantos** [comment]
Let me check if clj-yaml works with my document. Maybe there is a problem upstream.

**Comment by borkdude** [comment]
@luissantos Please let us know
